### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by benoit9126**
Improvement of the documentation. Creation of a `models` section #69.

### CODE REVIEW

**Comment by benoit9126** [comment]
@alihamdan @Saelyos I have improved what I could. Now, there are remaining TODO (single-phase transformer, split-phase transformer, Switch example, etc) that remain in the documentation. Could you please read it when you have time?

**Comment by alihamdan** [comment]
@benoit9126 this is ready now.

We have models docs and usage examples for all elements.

I also fixed all the links 🤞🏻 (the relative link hack you used earlier in the code docstring does not always work, it depends on the page you are in when you click the link, for example, works from `roseau.load_flow.models.line` but not from `roseau.load_flow.line`. Using `:doc:` instead always works 🍾 )

**Comment by benoit9126** [comment]
I will add some other modifications in this branch (Google Analytics, etc). @alihamdan @Saelyos Thanks! :+1:

Small question when reading the documentation. In such example, I think there is a problem with delta connected voltage source (extracted from the example on the page "three-phase transformer"):

```python
# Create a MV bus
bus_mv = Bus(id="bus_mv", phases="abc")

# ....

# Create a voltage source and connect it to the MV bus
voltages = 20e3 * np.exp([0, -2j * np.pi / 3, 2j * np.pi / 3])
vs = VoltageSource(id="vs", bus=bus_mv, voltages=voltages)
```

As it is a delta voltage source, its voltages should have been:

```python
import numpy as np
from roseau.load_flow.converters import calculate_voltages

potentials = 20e3/np.sqrt(3) * np.exp([0, -2j * np.pi / 3, 2j * np.pi / 3])
voltages = calculate_voltages(potentials, "abc")
# array([ 17320.50807569+10000.j,      0.        -20000.j,  -17320.50807569+10000.j])
```

**Comment by alihamdan** [comment]
I think both are correct. It depends on what you'd like to be your "reference" (angle 0 with the potential ref). At the end, voltage is relative and the results you get will depend on your definition but both are correct.

> Small question when reading the documentation. In such example, I think there is a problem with delta connected voltage source (extracted from the example on the page "three-phase transformer"):
> 
> ```python
> # Create a MV bus
> bus_mv = Bus(id="bus_mv", phases="abc")
> 
> # ....
> 
> # Create a voltage source and connect it to the MV bus
> voltages = 20e3 * np.exp([0, -2j * np.pi / 3, 2j * np.pi / 3])
> vs = VoltageSource(id="vs", bus=bus_mv, voltages=voltages)
> ```

In this example, the voltage `Uab` has angle 0 with the potential ref

> As it is a delta voltage source, its voltages should have been:
> 
> ```python
> import numpy as np
> from roseau.load_flow.converters import calculate_voltages
> 
> potentials = 20e3/np.sqrt(3) * np.exp([0, -2j * np.pi / 3, 2j * np.pi / 3])
> voltages = calculate_voltages(potentials, "abc")
> # array([ 17320.50807569+10000.j,      0.        -20000.j,  -17320.50807569+10000.j])
> ```

While in this example `Va` has the angle 0 with the potential ref.

In both cases you get a 20kV source with 120° between the phases.

**Pull request merged**
